### ISSUE TITLE
ImportError: No module named html

### ISSUE THREAD

**Issue by willupowers** [jwkvam/bowtie-demo#5]
See full issue here:
https://github.com/jwkvam/bowtie/issues/229

(py27bowtie) users-MacBook-Pro:bowtie-demo-master user$ ./example.py
Traceback (most recent call last):
  File "./example.py", line 7, in <module>
    from bowtie.html import Markdown
ImportError: No module named html

**Comment by jwkvam** [comment]
closing since https://github.com/jwkvam/bowtie/issues/229 was closed
